### ISSUE TITLE
Fix typos in Due Diligence  review template

### ISSUE THREAD

**Issue by mfdii** [cncf/toc#305] opened 2019-10-07 15:00 UTC
This [section](https://github.com/cncf/toc/blob/master/process/dd-review-template.md#introduction) has the following text/typos:

```The decision to graduate or promote a project depend on the TOC sponsors of the project performina dn documenting the evaluation process in deciding upon initial or continued inclusion of projects through a Technical Due Diligence ('Tech DD') exercise. ```

I wasn't sure of the original intent of the author, so I didn't know how best to change the sentence to fix it myself.

**Comment by ultrasaurus** [comment] 2019-12-17 16:42
Here's clarified wording based on my understanding of the process:

> Before a TOC vote on including a new project or promotion of a current project,  the TOC sponsors of the project perform Technical Due Diligence ('Tech DD'), resulting in a document, which aids in the evaluation process by other members of the TOC.

@michelleN @quinton-hoole what do you think?

**Comment by quinton-hoole** [comment] 2020-01-22 04:55
To be honest, it's not clear to me what the purpose of this Due Diligence Review Template is.

It appears to be largely a duplicate of material published elsewhere, for example:

[Due Diligence Guidelines](https://github.com/cncf/toc/blob/master/process/due-diligence-guidelines.md) and the few documents linked from there, for example:

https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc

and 

https://github.com/cncf/toc/blob/master/PRINCIPLES.md

I would suggest that this document be deleted, or at least have all the cut 'n paste from other canonical documents removed and replaced with references or similar.  The current document seems more confusing than useful.

Other opinions?

**Comment by ultrasaurus** [comment] 2020-01-22 19:25
Several of the SIGs are making additional templates for due diligence reviews, and I'd prefer to have a single template with the info that TOC wants/requires (and of course, SIGs can create additional area-specific templates or Q&A with *additional* info, but prefer we not all be creating different versions of the same thing

**Comment by erinaboyd** [comment] 2020-01-22 19:59
@quinton-hoole @ultrasaurus Quinton - As per our F2F in San Diego, we discussed creating a more clear process by which projects new to the process clearly understand how to get started and what steps to take. I believe we took away from that creating a flow and/or template for each level would be helpful. Though these documents do exist we either need a clearly way of knitting them together or a more granular process and examples so we can provide less 1:1 direction and more consistent communication with projects. Open to suggestions but at miniumum I think as SIG leads we need to agree to how we are going to move forward. And then what documents, process, etc... we create to support that.

**Comment by quinton-hoole** [comment] 2020-01-23 00:54
@erinaboyd @ultrasaurus   Having templates and workflows is fine.  But it will be important to tie all those back to the correct sources or truth provided by the TOC.  Otherwise, for example, the TOC's graduation criteria and technical due diligence guidelines will over time not be consistent with the templates.  I would prefer the templates to link back to the original sources of truth, rather than include partial cut 'n pastes of parts of them, with no links back to the originals (which is what we appear to have in this document in question).

**Comment by amye** [comment] 2021-12-14 17:26
Closing as we've updated these more recently

**Closed by amye** 2021-12-14 17:26 UTC
