### ISSUE TITLE
[PROJECT ONBOARDING] OpenGitOps

### ISSUE THREAD

**Issue by caniszczyk** [cncf/toc#584] opened 2020-12-17 15:58 UTC
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project. 

From the project side, please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Owners file: Please add a link to your owners file to this issue, this is used to be able to create your maintainers mailing list. 
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices) followed
- [x] Website: Analytics transferred
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by lukaszgryglicki** [comment] 2020-12-18 12:14
Hi, can you point me to this project's GitHub repo or a TOC PR with more details? I wanted to start adding the DevStats page but I can't find enough details.

**Comment by mjpitz** [comment] 2020-12-18 16:16
@lukaszgryglicki : https://github.com/fluxcd/gitops-working-group

**Comment by lukaszgryglicki** [comment] 2020-12-18 16:18
OK, thanks, any plans to move to a separate GitHub org?
What is the maturity level? Sanbox? Incubating?

**Comment by mjpitz** [comment] 2020-12-18 16:29
They're just starting. The first meeting was on December 10th.

**Comment by lukaszgryglicki** [comment] 2020-12-22 08:13
DevStats [test](https://gitopswg.teststats.cncf.io) and [prod](https://gitopswg.devstats.cncf.io) pages added.

**Comment by todaywasawesome** [comment] 2021-01-08 19:08
Repo has migrated to here https://github.com/gitops-working-group/gitops-working-group/

**Comment by amye** [comment] 2021-01-26 20:04
Welcome in! I've added you to the CNCF sandbox projects page with the CNCF icon until we get a logo together.
Things to do:  
* There's no website beyond Github, right? 
* GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
* Landscape will be under Continuous Integration & Delivery, but that needs a logo too 
* Trademarks might not be necessary here

**Comment by amye** [comment] 2021-02-08 23:10
@todaywasawesome: I'm marking off a bunch of things in here because I'm assuming there's no website beyond GH. Let' me know if I'm in error.

**Comment by dj1k** [comment] 2021-02-11 15:21
Thank you Amye! We'll be resolving most of these issues shortly.

**Comment by amye** [comment] 2021-02-23 19:40
For logo, LP-7167 is in with our team to get you all a logo.

**Comment by amye** [comment] 2021-03-02 20:45
@dj1k: checking in here!

**Comment by scottrigby** [comment] 2021-03-24 21:05
Hey @amye 👋 

- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

Just invited them as owners to the https://github.com/gitops-working-group gh org ✔️ 

- [ ] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/

I've opened an explicit issue in the GitOps WG repo: https://github.com/gitops-working-group/gitops-working-group/issues/94

- [ ] CNCF Welcome Email Sent to confirm maintainer list access

Is there anything we need to do to help with this?

- [ ] Schedule monthly project sync with CNCF staff

I'm happy to help coordinate this in collaboration with @dj1k

**Comment by amye** [comment] 2021-03-24 21:13
Artwork is the thing that's really hanging us up, where are we on that?

**Comment by scottrigby** [comment] 2021-03-24 21:55
The artwork logo design so far is in this github discussion proposal by @iboonox: https://github.com/gitops-working-group/gitops-working-group/discussions/63#discussioncomment-478223.

I just commented on the next steps again: https://github.com/gitops-working-group/gitops-working-group/discussions/63#discussioncomment-527026, and reached out to @iboonox. The next planned step has been to submit a PR to https://github.com/cncf/artwork once the [Sandbox project name change proposal](https://github.com/gitops-working-group/gitops-working-group/discussions/64) reached consensus, which it now has https://github.com/gitops-working-group/gitops-working-group/discussions/64#discussioncomment-505062. I'll keep this issue updated on progress 👍

**Comment by scottrigby** [comment] 2021-03-24 21:55
Regarding the project name change, consensus on the new Sandbox project name is `OpenGitOps`, while the actual WG under CNCF SIG App Delivery will remain `GitOps Working Group`. Cornelia clarified that this is consistent with the plan from the Jan 26 sandbox review: https://github.com/gitops-working-group/gitops-working-group/discussions/64#discussioncomment-518708.

**Comment by scottrigby** [comment] 2021-03-24 21:56
Also
- [ ] Website: Analytics transferred

Will do once the website is up. I made an explicit issue to track this: https://github.com/gitops-working-group/gitops-working-group/issues/95

**Comment by amye** [comment] 2021-03-24 23:01
@scottrigby: Trademarks is an outstanding issue as well, we have our agreements in: https://github.com/cncf/foundation/tree/master/agreements

**Comment by scottrigby** [comment] 2021-03-25 04:04
👌 Added https://github.com/gitops-working-group/gitops-working-group/issues/97 to track trademark assignment. Pinged in Slack with a few questions on that one

**Comment by scottrigby** [comment] 2021-03-25 04:28
- [ ] Artwork: Ensure logos present on https://github.com/cncf/artwork

I don't believe this one is done. Made tracking issue: https://github.com/gitops-working-group/gitops-working-group/issues/100 in progress

**Comment by scottrigby** [comment] 2021-04-01 17:48
Hi Amye 👋 

> Trademarks: transfer any trademark and logo mark assets over to the LF

1. Just waiting for confirmation about one thing – should not be long. I believe we're using the no reg agreement.
2. Artwork status:
    - Design/logos have consensus 🎉  https://github.com/gitops-working-group/gitops-working-group/discussions/63#discussioncomment-558670
    - The detailed steps for supplying CNCF with artwork are in this issue https://github.com/gitops-working-group/gitops-working-group/issues/100

> GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership

Done for both GitHub orgs:
- https://github.com/gitops-working-group
- https://github.com/open-gitops

> Website: Analytics transferred

No website yet. But issue to track this is here https://github.com/gitops-working-group/gitops-working-group/issues/95


> 
> These are for CNCF staff to do:
> Update https://landscape.cncf.io
> ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
> CNCF Welcome Email Sent to confirm maintainer list access
> Schedule monthly project sync with CNCF staff

**Comment by scottrigby** [comment] 2021-04-01 21:44
>1. Just waiting for confirmation about one thing – should not be long. I believe we're using the no reg agreement.
Confirmed 👍

**Comment by scottrigby** [comment] 2021-04-12 19:47
@amye logo assets are added to the GWG repo for now https://github.com/gitops-working-group/gitops-working-group/pull/124

**Comment by lukaszgryglicki** [comment] 2021-04-13 05:36
We will also need artwork PR in [cncf/artwork](https://github.com/cncf/artwork).

**Comment by scottrigby** [comment] 2021-04-26 03:10
> We will also need artwork PR in [cncf/artwork](https://github.com/cncf/artwork).

@lukaszgryglicki Thanks 👍 per @amye in https://github.com/gitops-working-group/gitops-working-group/pull/124#issuecomment-825154418 two PRs made:
- https://github.com/cncf/artwork/pull/233
- https://github.com/cncf/artwork/pull/234

**Comment by scottrigby** [comment] 2021-04-26 03:18
BTW per maintainers-related checklist items, the [MAINTAINERS](https://github.com/gitops-working-group/gitops-working-group/blob/main/MAINTAINERS) file has been updated https://github.com/gitops-working-group/gitops-working-group/pull/136

**Comment by todaywasawesome** [comment] 2021-04-26 21:37
The maintainers have all confirmed they've read the onboarding docs https://github.com/gitops-working-group/gitops-working-group/issues/94

**Comment by amye** [comment] 2021-04-26 22:29
Super! 
* Artwork is the thing that's hanging the landscape up, so I know where that is. 
* Website analytics are in progress, https://github.com/gitops-working-group/gitops-working-group/issues/95 
* Trademarks are the last remaining!

**Comment by lukaszgryglicki** [comment] 2021-04-27 05:36
Hi, I see there are 2 PRs for artwork - which artwork DevStats should use after PR(s) got merged?

**Comment by scottrigby** [comment] 2021-05-14 23:13
@lukaszgryglicki the OpenGitOps artwork PR was for the Sandbox project. The GitOps WG artwork was under "other", and added just because the same person also made a cool logo for the GitOps WG under SIG App Delivery 😄

**Comment by lukaszgryglicki** [comment] 2021-05-16 06:09
So which one should I use in DevStats?

**Comment by poconnor1** [comment] 2021-05-26 11:40
Hi @scottrigby 
Hope you are well. Checking in here on the status of website analytics (which I knew were in progress) gitops-working-group/gitops-working-group#95
and the trademarks! Those are the last items remaining :)

Thank you!

**Comment by scottrigby** [comment] 2021-05-28 17:47
@lukaszgryglicki For now, github.com/open-gitops is probably best for devstats, since it's the sandbox project. Note that there is a [CNCF service desk ticket](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-791) and github support ticket to be given ownership of the unused "opengitops" (all one word) github repo. If/when we do, devstats should point there. However if we do, we will set up a proper github redirect, so it should work regardless 😄 

@poconnor1 does CNCF have specific requirements for website analytics? We are working on getting a website up and running. @todaywasawesome is leading that now.

The trademark and account assignment is in progress, tracked by [this CNCF Service Desk ticket](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-789) ⏳ 😸 

@amye Artwork is merged, but are we waiting for trademark and assignments to complete before updating the CNCF landscape and website? https://www.cncf.io/sandbox-projects/ Just checking 

Thanks everyone for your patience and support so far! Excited to see this onboarding wrap up 😅

**Comment by lukaszgryglicki** [comment] 2021-06-01 08:57
OK I'll use [this](https://github.com/cncf/artwork/tree/master/projects/opengitops/icon/color) in DevStats pages.

**Comment by amye** [comment] 2021-10-04 16:55
@scottrigby: Updating here: "Trademarks: transfer any trademark and logo mark assets over to the LF"  - this is still over in our queue. 
We've got a separate conversation going for analytics, but Google Analytics is our preference.

**Comment by amye** [comment] 2021-10-06 20:44
Renaming issue to reflect the actual name of the group.

**Comment by amye** [comment] 2021-12-14 17:41
@scottrigby - this can be closed if we have the final trademark paperwork signed, see Servicedesk!

**Comment by amye** [comment] 2022-03-16 23:44
And complete here!

**Closed by amye** 2022-03-16 23:44 UTC
Labels: sandbox, project onboarding, trademarks
