### ISSUE TITLE
[PROJECT ONBOARDING] Kubeflow

### ISSUE THREAD

**Issue by amye** [cncf/toc#1139] opened 2023-08-04 18:46 UTC
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/legal/trademark-usage>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk - project-onboarding@cncf.io is the best email to send those to
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: https://github.com/enterprises/cncf
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to projects@cncf.io
- [x] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Book time with the team with <http://project-meetings.cncf.io>
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by amye** [comment] 2023-08-04 18:47
@mrbobbytables  - catching up here!

**Comment by zijianjoy** [comment] 2023-08-04 18:58
cc Current kubeflow steering committee : @jbottum @theadactyl @james-jwu

**Comment by zijianjoy** [comment] 2023-08-04 19:00
Looking at the task `Devstats: add to devstats https://devstats.cncf.io/`, looks like we already have `kubeflow` in the dashboard, https://kubeflow.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m, do we consider this item done?

**Comment by amye** [comment] 2023-08-04 19:01
Yep, that's already taken care of, this issue is just to track everything for onboarding.

**Comment by zijianjoy** [comment] 2023-08-04 19:07
Thanks @amye !

Regarding the task of `Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy`, kubeflow side has an ongoing issue to track its progress: https://github.com/kubeflow/community/issues/614

**Comment by amye** [comment] 2023-08-04 19:22
> Thanks @amye !
> 
> Regarding the task of `Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy`, kubeflow side has an ongoing issue to track its progress: [kubeflow/community#614](https://github.com/kubeflow/community/issues/614)

This actually looks like it's a Code of Conduct adoption issue?

**Comment by zijianjoy** [comment] 2023-08-04 19:26
@amye You are right, it should be related to `GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub` task.

**Comment by amye** [comment] 2023-09-29 01:12
@zijianjoy - we can probably work on the rest of these tasks as we get that sorted out. 
Anything we can help with?

**Comment by zijianjoy** [comment] 2023-09-29 15:46
@amye The OSPO on Google side has reached out to CNCF about the IP transfer, however, I don't have visibility to the progress. If that is finished, we can mark this item as done. Please let me know if this is not the case and I can reach out to CNCF for help.

**Comment by amye** [comment] 2023-09-29 16:32
There's a thread with the right people for trademarks!

**Comment by annajung** [comment] 2023-10-31 16:44
PR https://github.com/cncf/foundation/pull/662 is open for the following:
> Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it

**Comment by annajung** [comment] 2023-11-01 17:36
Issue https://github.com/kubeflow/community/issues/656 can be used to track progress for the following:
> Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction

> Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/

> Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md

> Understand the trademark guidelines: https://www.linuxfoundation.org/legal/trademark-usage

> Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist

**Comment by annajung** [comment] 2023-11-03 13:59
### Roles
Roles within Kubeflow are defined in the [community membership doc](https://github.com/kubeflow/community/blob/master/wgs/community-membership.md), where it lists 4 roles: member, reviewer, approver subproject owner, and the requirements and responsibilities of each role.

- [Community membership](https://github.com/kubeflow/community/blob/master/wgs/community-membership.md)

### Working Groups
There are [multiple working groups](https://github.com/kubeflow/community/blob/master/wg-list.md) under the Kubeflow org that are responsible for different components of the project. Working Group charter, governance, and requirements can be found at [/kubeflow/community/wgs](https://github.com/kubeflow/community/tree/master/wgs)

- [List of Working Groups](https://github.com/kubeflow/community/blob/master/wg-list.md)
- [Working Group Charter Guide](https://github.com/kubeflow/community/blob/master/wgs/wg-charter.md)
- [Working Group Governance Requirements](https://github.com/kubeflow/community/blob/master/wgs/wg-governance-requirements.md)
- [Working Group roles and organization](https://github.com/kubeflow/community/blob/master/wgs/wg-governance.md)
- [Creation and Retirement of Working Group](https://github.com/kubeflow/community/blob/master/wgs/wg-lifecycle.md)

### Leadership
Kubeflow community accepted a [proposal of three governance groups](https://github.com/kubeflow/community/blob/master/proposals/GOVERNANCE.md): Kubeflow Steering Committee (KSC), Kubeflow Conformance Committee (KCC), and Kubeflow Technical Oversight Committee (KTOC), as part of their open governance effort.

In addition to the proposal of the three governance groups, Kubeflow has [3 interim steering committees](https://github.com/kubeflow/community/blob/master/proposals/STEERING-COMMITTEE.md) responsible for establishing KSC, KCC, and KTOC charters. 

At this time, the KSC charter has been defined by the interim steering committees and there is a PR https://github.com/kubeflow/community/pull/650 open for community review and feedback. Once the PR is merged or in parallel, the Kubeflow community is planning to hold the first KSC election.

- [Proposal of three governance](https://github.com/kubeflow/community/blob/master/proposals/GOVERNANCE.md)
- [Interim Kubeflow Steering Committee](https://github.com/kubeflow/community/blob/master/proposals/STEERING-COMMITTEE.md)
- [KSC Charter](https://github.com/kubeflow/community/pull/650)

All governance related can be found at [kubeflow/community repo](https://github.com/kubeflow/community/tree/master)

@amye Does this meet this following requirement?

>  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/

**Comment by annajung** [comment] 2023-11-03 14:15
@amye could you clarify if this is a hard requirement? There is a concern regarding migrating > 9,000 users in the current Kubeflow slack workspace to CNCF and possibly to one flat channel under CNCF when there are multiple active channels within the current slack workspace for different purposes. (ref https://github.com/kubeflow/community/issues/615)

Also, Kubeflow slack workspace is currently under the free plan which deletes messages after a certain amount of days. Due to this issue, many community members have been asking to find an alternative or move to a paid plan to ensure the messages are stored and searchable in the future. 

Instead of migrating to the CNCF workspace, is there a way CNCF can help with managing a paid plan for the current Kubeflow workspace? Or is there any other alternative you can suggest?

> Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)

**Comment by terrytangyuan** [comment] 2023-11-03 14:45
Just to share our experience from Argo project Slack channel migration. We had a very popular Slack workspace dedicated to Argo, but we eventually switched to CNCF Slack and closed the Argo Slack workspace. We prefixed all Slack channels with "argo-" so it's easy to identify and search for relevant channels. Some main ones are listed here: https://argoproj.github.io/community/join-slack

Some quick stats on major channels:
* #argo-cd: 12k members
* #argo-workflows: 6k members
* #argo-events: 2.5k members
* #argo-rollouts: 2.7k members
* #argo-contributors: 1k members
* #argo-announcements: 2k members

Overall, the migration was quite successful, easier to find for existing CNCF users, and easier to collaborate with CNCF ecosystem projects. Hope this helps.

**Comment by zijianjoy** [comment] 2023-11-03 15:46
> but we eventually switched to CNCF Slack and closed the Argo Slack workspace.

Hello @terrytangyuan , thank you for sharing your experience. Would you like to elaborate the process of such migration? 
- What action did Argo Slack users need to take for such migration?
- How does the permission configuration look like for Argo- channels? (Does the argo steering committee have permission to manage/create argo- channel?)
- How much percentage of Slack users did we successfully migrate to CNCF slack?

**Comment by terrytangyuan** [comment] 2023-11-03 20:26
> Would you like to elaborate the process of such migration?

We archive the channels in the original Slack workspace on a schedule. See https://github.com/argoproj/argoproj/issues/47 for details. We announced/reminded regularly, started supporting users in CNCF channels, and eventually the old Slack workspace became inactive.

> What action did Argo Slack users need to take for such migration?
They could just visit the link to join CNCF Slack and different channels: https://argoproj.github.io/community/join-slack. Once joined, they no longer have to go back to the original Slack workspace since nobody was responding to questions there.

> How does the permission configuration look like for Argo- channels? (Does the argo steering committee have permission to manage/create argo- channel?)

I think only CNCF can manage existing channels. You can create new channels but at some point CNCF will take over.

> How much percentage of Slack users did we successfully migrate to CNCF slack?

I don't remember the exact number but we had thousands of users in the old Slack. Once we migrated, it would just become more popular over time if marketing/communication was done regularly. It was quite successful for us at least.

**Comment by annajung** [comment] 2023-11-07 17:25
These items are complete, thank you! 

> Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk - [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io) is the best email to send those to

An email was sent on Nov 7th and confirmation was also received.

> Is your project in its own separate neutral github organization?

The kubeflow project is already in a separate neutral GitHub org, under Kubeflow

**Comment by zijianjoy** [comment] 2023-11-07 20:15
> Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)

The current Google Analytics account is internal only account. We are not able to add external user to this GA account. But we can add CNCF GA account tracking ID to kubeflow website. Would you like to share the information which allows us to inject your analytics account to kubeflow website? @amye

**Comment by amye** [comment] 2023-11-07 20:17
> > Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
> 
> The current Google Analytics account is internal only account. We are not able to add external user to this GA account. But we can add CNCF GA account tracking ID to kubeflow website. Would you like to share the information which allows us to inject your analytics account to kubeflow website? @amye

Oof, that is going to be a mess. @nate-double-u, what's the best path forward here? Losing the historical data is not great for anyone.

**Comment by zijianjoy** [comment] 2023-11-07 21:21
> > > Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
> > 
> > 
> > The current Google Analytics account is internal only account. We are not able to add external user to this GA account. But we can add CNCF GA account tracking ID to kubeflow website. Would you like to share the information which allows us to inject your analytics account to kubeflow website? @amye
> 
> Oof, that is going to be a mess. @nate-double-u, what's the best path forward here? Losing the historical data is not great for anyone.

From what I can see, the current GA account is not collecting data any more because it hasn't been moved to Google Analytics 4 (G44) property: https://support.google.com/analytics/answer/12938611#zippy=%2Cin-this-article. So there is no historic data to move. I think we should just focus on setting up a new analytics account at this point.

**Comment by amye** [comment] 2023-11-07 21:22
> > > > Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
> > > 
> > > 
> > > The current Google Analytics account is internal only account. We are not able to add external user to this GA account. But we can add CNCF GA account tracking ID to kubeflow website. Would you like to share the information which allows us to inject your analytics account to kubeflow website? @amye
> > 
> > 
> > Oof, that is going to be a mess. @nate-double-u, what's the best path forward here? Losing the historical data is not great for anyone.
> 
> From what I can see, the current GA account is not collecting data any more because it hasn't been moved to Google Analytics 4 (G44) property: https://support.google.com/analytics/answer/12938611#zippy=%2Cin-this-article. So there is no historic data to move. I think we should just focus on setting up a new analytics account at this point.

Oh, if that's all, yes - we can create a new one. The historical data is helpful for project journey reports, but if it's already not an option then we can start over.

**Comment by zijianjoy** [comment] 2023-11-07 21:29
> > > > > Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
> > > > 
> > > > 
> > > > The current Google Analytics account is internal only account. We are not able to add external user to this GA account. But we can add CNCF GA account tracking ID to kubeflow website. Would you like to share the information which allows us to inject your analytics account to kubeflow website? @amye
> > > 
> > > 
> > > Oof, that is going to be a mess. @nate-double-u, what's the best path forward here? Losing the historical data is not great for anyone.
> > 
> > 
> > From what I can see, the current GA account is not collecting data any more because it hasn't been moved to Google Analytics 4 (G44) property: https://support.google.com/analytics/answer/12938611#zippy=%2Cin-this-article. So there is no historic data to move. I think we should just focus on setting up a new analytics account at this point.
> 
> Oh, if that's all, yes - we can create a new one. The historical data is helpful for project journey reports, but if it's already not an option then we can start over.

Sounds good, @nate-double-u Please feel free to comment here for how to move forward integrating with CNCF analytics account. The kubeflow website is located in https://github.com/kubeflow/website

**Comment by nate-double-u** [comment] 2023-11-07 23:58
Since I'm onsite at KubeCon, maybe I can ping @chalin for a consult here as I'm not sure how quickly I'll be able to look at this.

Patrice, is this something you may be able to help with?

**Comment by chalin** [comment] 2023-11-08 13:19
Certainly, I'm on it!

**Comment by chalin** [comment] 2023-11-08 13:22
Can someone grant me access to Kubeflow's Netlify account?

**Comment by chalin** [comment] 2023-11-08 13:53
Here's the issue I'm using to track the setup of GA4:

- https://github.com/kubeflow/website/issues/3620

**Comment by annajung** [comment] 2023-11-08 16:07
PR https://github.com/kubeflow/internal-acls/pull/624 is open for the following:
>  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: https://github.com/enterprises/cncf

PR https://github.com/kubeflow/community/pull/658 is open for the following:
> GitHub: ensure that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub

PR https://github.com/kubeflow/website/pull/3621 is open for the following:
> Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).

This is also in progress with help from @akgraner, a PR will be made once artwork is available to be submitted
>  Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

**Comment by annajung** [comment] 2023-11-15 17:33
Issue https://github.com/kubeflow/community/issues/661 can be used to track progress for the following:

>  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

**Comment by chalin** [comment] 2023-11-17 09:25
@annajung et al.: regarding the following item in the opening-comment checklist:

> - [ ] Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)

There will be no need to transfer analytics once the following PR is merged because the website will be configured to use the new CNCF GA4 site tag created under the CNCF Project account:

- https://github.com/kubeflow/website/pull/3627

Also, once the above PR is merged, I will no longer require access to the Netlify account, though granting someone from the CNCF access (possibly at least projects@cncf.io) is probably still advisable. /cc @amye

**Comment by zijianjoy** [comment] 2023-11-25 22:33
I have created https://github.com/coreinfrastructure/best-practices-badge/issues/2076 to transfer badge entry ownership to active kubeflow member to continue the work.

> OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en

**Comment by zijianjoy** [comment] 2023-11-25 22:36
I have approved the following PRs:
- https://github.com/coreinfrastructure/best-practices-badge/issues/2076
- https://github.com/kubeflow/internal-acls/pull/624

**Comment by annajung** [comment] 2023-11-29 17:45
Hi @amye @Cmierly, following up on two comments:

1. Could you see if https://github.com/cncf/toc/issues/1139#issuecomment-1792488467 is sufficient to mark the following requirement as completed? In addition, if it's not, could you share what you're looking for to complete this task.
>  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/

2. Could you also review https://github.com/cncf/toc/issues/1139#issuecomment-1792515783? We are looking for what options are available for us with slack migration to determine what's the best way to move forward with some of the concerns raised by the community
>  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)

**Comment by zijianjoy** [comment] 2023-11-29 22:23
Thank you @Cmierly , servicedesk.cncf.io asks for login but I don't have an account, nor can I sign up for one. What kind of permission is needed for Slack migration?


![BHuT7qx5ZFwVeh5](https://github.com/cncf/toc/assets/37026441/8fed1a60-1a5c-40c7-ad21-0078565fd542)

**Comment by akgraner** [comment] 2023-12-01 15:11
Thank you Anna!

**Comment by jbottum** [comment] 2023-12-07 22:53
@Cmierly @amye I am reviewing with James Wu.   We are both on the Kubeflow Steering Committee and would like to know if we can continue to use the existing Kubeflow slack channels.   Is this an option for Kubeflow as a CNCF project ?

**Comment by zijianjoy** [comment] 2023-12-08 18:33
@amye Can we designate Kubeflow Steering Committee members (3 people) as Channel Managers of Kubeflow channels in CNCF Slack Workspace?(https://slack.com/help/articles/8328303095443-Understand-Channel-Managers-in-Slack), this allows CNCF admin to delegate some management work to Kubeflow community.

**Comment by thesuperzapper** [comment] 2023-12-14 01:03
I think it would be great to have a few channels on the CNCF Slack (for those who might look for us there), in addition to our existing Kubeflow-specific Slack server (just like the Kubernetes community does).

Having our own Slack lets us keep everything organized. There are MANY components of Kubeflow and different interest groups, who all would have a hard time if we forced them into a small number of channels.

For reference, we have 38 public channels that were active in the last 6 months, and that's not to speak of private messages/channels which make up 75% of the total activity.

The Kubflow Slack has gained quite a few members in the last few months (we recently hit 10k!):

![5320bd4e-5d5d-4eac-a989-65b52b6a9e4c](https://github.com/cncf/toc/assets/5735406/3b1cfc4d-7b01-4812-a32e-b7b34a9d21e3)

For reference, over the last 3 years, we have maintained an average of 400-900 weekly active users on Slack (in the 3 years before that, it was a little less).

![Screenshot 2023-12-13 at 16 58 07](https://github.com/cncf/toc/assets/5735406/f2c69a95-5cd4-48cc-a58b-c9e01729d3a3)

**Comment by amye** [comment] 2024-01-17 22:10
re: Slack channels - let's move this one into servicedesk because that may be possible - but it may also be complicated. Separately, that's a great way to check your servicedesk access!

**Comment by zijianjoy** [comment] 2024-01-18 00:48
@amye Sounds good! We can move the slack migration item off from the onboarding checklist. Will continue discussion in servicedesk.

**Comment by bhack** [comment] 2024-01-19 13:14
> Insights: add to LFX Insights https://insights.v3.lfx.linuxfoundation.org/

Any update about this point?

**Comment by krook** [comment] 2024-01-19 20:47
> > Insights: add to LFX Insights https://insights.v3.lfx.linuxfoundation.org/
> 
> Any update about this point?

Hi @bhack,

You are now onboarded onto the CNCF GitHub Enterprise account. However, we still need to add `thelinuxfoundation` as an owner of your org. 

Once `thelinuxfoundation` is an owner, we can then onboard you to LFX Insights (which is a matter of adding an app, similar to adding the DCO bot) which uses read only, public data to drive the reports on the [Insights dashboard](https://insights.lfx.linuxfoundation.org/foundation/cncf).

That would mark both of these checklist items as up-to-date and complete (and it supersedes the need to add Chris and I as owners):

- [ ] GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership while we onboard you to our GitHub Enterprise instance: <https://github.com/enterprises/cncf>
- [ ] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>

You can learn more about Insights here:

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)

Please let me know if you have any questions about adding `thelinuxfoundation` as an owner of your org and/or boarding Insights.

**Comment by zijianjoy** [comment] 2024-01-22 20:04
@krook All CNCF point-of-interest as mentioned are invited to the Kubeflow admin roles in https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml#L7-L17. They will need to accept the invite in order to be part of Kubeflow. Daniel, I see that you have already joined Kubeflow group, so feel free to move forward with the onboarding items mentioned.

**Comment by Cmierly** [comment] 2024-02-08 21:19
@zijianjoy 
I've updated the checklist so it should be accurate as of today!

**Comment by zijianjoy** [comment] 2024-02-08 23:43
@Cmierly Thank you! I think the following items should be marked as completed as well:

```
- [ ]  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
- [ ]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [ ]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [ ]  Understand the trademark guidelines: https://www.linuxfoundation.org/legal/trademark-usage
- [ ]  Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [ ]  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
```

**Comment by zijianjoy** [comment] 2024-02-14 00:19
Update on OpenSSF Best Practices Badge: I am able to get access to the kubeflow badge entry and I have run a pass on the questionnaire: https://www.bestpractices.dev/en/projects/2660.

- [x] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge

**Comment by terrytangyuan** [comment] 2024-02-14 01:24
> GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project

@zijianjoy The KSC also decided to use DCO going forward so can we disable CLA check and enable DCO App at org level going forward.

**Comment by zijianjoy** [comment] 2024-02-14 02:05
> > GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
> 
> @zijianjoy The KSC also decided to use DCO going forward so can we disable CLA check and enable DCO App at org level going forward.

Thanks, I have enabled DCO in kubeflow repos. I will give it a few days to test it out that DCO is being enforced across Kubeflow and people are able to develop using the new approach. Then we will decide on when to disable CLA.

**Comment by zijianjoy** [comment] 2024-03-26 20:42
Update: We have done the following list of items, please update issue description accordingly, thank you!

| Status 	| Requirement                                                                                                                                                                                        	| Relevant issues/PR                                                     	|
|--------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|------------------------------------------------------------------------	|
| Done   	| Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy                                                                               	| https://github.com/kubeflow/community/issues/661                       	|
| Done   	| OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en                                                                             	| https://github.com/coreinfrastructure/best-practices-badge/issues/2076 	|
| Done   	| GitHub: ensure that that the CNCF Code of Conduct (or your adopted version of it) are explicitly referenced at the project's README on GitHub                                                      	| https://github.com/kubeflow/community/pull/658                         	|
| Done   	| Website: ensure LF footer is there and website guidelines followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub). 	| https://github.com/kubeflow/website/pull/3622                          	|

**Comment by Cmierly** [comment] 2024-03-27 20:42
@zijianjoy I've updated the checklist and it should be accurate as of today!

**Comment by rimolive** [comment] 2024-04-02 12:23
I believe this item is done.
```
 Insights: add to LFX Insights https://insights.v3.lfx.linuxfoundation.org/
```
Based on the following: https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=kubeflow

**Comment by krook** [comment] 2024-05-23 20:09
FYI, details on Insights now that you're [onboarded](https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=kubeflow).

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)
- [Insights support](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4?requestGroup=54)
- [Insights feedback](https://app.slack.com/client/T08PSQ7BQ/C0703RGFDA6)

**Comment by krook** [comment] 2024-07-18 21:06
@rimolive @zijianjoy @terrytangyuan,

It looks like we're very close to closing out this checklist. The remaining items are:

- [ ] Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63
- [ ] Book time with the team with http://project-meetings.cncf.io
- [ ] Adopt a license scanning tool, like FOSSA or Snyk

The first one should be straightforward. You can use projects@cncf.io as the "LF Stakeholder email".

The second one is completely optional but let us know if you want to hop on Zoom to answer any other questions.

The third @RobertKielty can help you with.

**Comment by zijianjoy** [comment] 2024-07-22 03:46
Hello @krook , thank you for following up on this issue.

Regarding `transfer domain to the CNCF`: I have created https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2127 and is currently pending for Shah Ahmadzai to share an update.

Regarding license scanning tool, KFP (Kubeflow Pipelines) is currently using the following tools for scanning license:

- Frontend: We are using yarn license and `license-checker`: https://github.com/kubeflow/pipelines/blob/master/frontend/gen_licenses.js
- Backend: We are using https://github.com/google/go-licenses for license scanning.

**Comment by RobertKielty** [comment] 2024-09-04 08:41
There is a Kubeflow Team is now on FOSSA.

Two registered maintainers and one additional contributor have sucessfully accepted invites to join the CNCF Organizaion on FOSSA and I have addedm them to the team as Team Admins.

The maintainers are @rimolive @StefanoFioravanzo 
@tarilabs has also been added as a Team Admin.

**Comment by tarilabs** [comment] 2024-09-04 08:48
> Two registered maintainers and one additional contributor have sucessfully accepted invites to join the CNCF Organizaion on FOSSA and I have addedm them to the team as Team Admins.

![image](https://github.com/user-attachments/assets/a78d67af-f22c-420d-97e4-a7c46d844a07)

**Comment by tarilabs** [comment] 2024-09-04 08:51
Not sure if applicable, but I'd also wire the loop here, we need to find the owner of the "Main" Kubeflow YouTube channel, as the KF community currently can only manage the "community channel (ex-kubeflow dojo)"
- [ ] https://github.com/kubeflow/community/issues/745

**Comment by juliusvonkohout** [comment] 2024-09-04 10:03
> There is a Kubeflow Team is now on FOSSA.
> 
> Two registered maintainers and one additional contributor have sucessfully accepted invites to join the CNCF Organizaion on FOSSA and I have addedm them to the team as Team Admins.
> 
> The maintainers are @rimolive @StefanoFioravanzo @tarilabs has also been added as a Team Admin.

Does it make sense to add more people?

**Comment by tarilabs** [comment] 2024-09-04 10:09
> Does it make sense to add more people?

yes, as was also called out [here](https://github.com/kubeflow/model-registry/issues/323#:~:text=If%20you%20are%20a%20Kubeflow%20member%20reading%20this%20issue%20and%20you%20need%20to%20be%20added%20in%20the%20FOSSA%20tool%2C%20you%20can%20reach%20out%20to%20myself%2C%20%40rimolive%20and%20%40terrytangyuan%20to%20be%20added%20in%20the%20existing%20group%2C%20or%20ask%20a%20SC%20representative%20to%20manage%20the%20service%20desk%20request%20for%20you/your%20KF%20project.): 

> If you are a Kubeflow member reading this issue and you need to be added in the FOSSA tool, you can reach out to myself, @rimolive and @terrytangyuan to be added in the existing group, or ask a SC representative to manage the service desk request for you/your KF project.

You can let me know your FOSSA login, happy to add you to the FOSSA team mentioned in https://github.com/cncf/toc/issues/1139#issuecomment-2328279589
Please note I cannot invite for a FOSSA login (that is CNCF Service Desk ticket, for which KF SC representative can manage for you) but happy to do the chore work on the FOSSA side.

**Comment by thesuperzapper** [comment] 2024-09-04 10:16
@RobertKielty @tarilabs I seem to be on the CNCF FOSSA, but I'm not in the kubeflow team.

**Comment by tarilabs** [comment] 2024-09-04 10:19
> @RobertKielty @tarilabs I seem to be on the CNCF FOSSA, but I'm not in the kubeflow team.

done 👍

**Comment by juliusvonkohout** [comment] 2024-09-04 10:29
@tarilabs i am on foss as wel with my github tag @gmail.com

**Comment by zijianjoy** [comment] 2024-09-10 18:53
>  Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

Update: Google has completed domain transfer to CNCF, Rudy Grigar on the CNCF side has confirmed that the transfer is successful. 

I believe we can mark this issue as completed. Truly appreciate everyone on contributing their effort to make this happen!

**Comment by Cmierly** [comment] 2024-09-10 18:57
With the domain transfer complete, Kubeflow has now completed Onboarding!
Congrats!

**Closed by Cmierly** 2024-09-10 18:57 UTC
Labels: incubation, project onboarding

**Comment by terrytangyuan** [comment] 2024-09-11 00:15
Thank you everyone for helping with this! Truly a team effort!

**Comment by thesuperzapper** [comment] 2024-09-11 06:05
@Cmierly just to clarify, we have some DNS changes that we actually need on `kubeflow.org`, is this now only possible by CNCF staff?
